// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppIcon: typeof import('./../components/common/AppIcon.vue')['default']
    AppTabbarItem: typeof import('./../components/common/AppTabbarItem.tsx')['default']
    AppTabber: typeof import('./../components/common/AppTabber.tsx')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    OrderList: typeof import('./../components/OrderList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Suspense: typeof import('vue')['Suspense']
    Teleport: typeof import('vue')['Teleport']
    Transition: typeof import('vue')['Transition']
    TransitionGroup: typeof import('vue')['TransitionGroup']
  }
}
